# Generated by Django 6.0.4 on 2026-05-08 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('utm_source', models.CharField(blank=True, max_length=50)),
                ('utm_medium', models.CharField(blank=True, max_length=50)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
                ('custom_fields', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referrer_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_contacts', to='crm.contact')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stage', models.CharField(max_length=100)),
                ('product_of_interest', models.CharField(blank=True, max_length=255)),
                ('product_category', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('skipped_stages', models.JSONField(default=list)),
                ('is_closed', models.BooleanField(default=False)),
                ('closed_result', models.CharField(blank=True, max_length=20)),
                ('custom_fields', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_contacted_at', models.DateTimeField(blank=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='crm.contact')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(help_text='stage_change, note_added, auto_advance, etc.', max_length=50)),
                ('description', models.TextField()),
                ('performed_by', models.CharField(default='system', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('meta', 'Meta (Facebook/Instagram)'), ('google', 'Google Ads'), ('tiktok', 'TikTok'), ('web', 'Página web'), ('referral', 'Referido')], default='web', max_length=20)),
                ('utm_source', models.CharField(blank=True, max_length=50)),
                ('utm_medium', models.CharField(blank=True, max_length=50)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
                ('landing_page_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='crm.lead')),
                ('referrer_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_leads', to='crm.contact')),
            ],
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['tenant', 'phone_number'], name='crm_contact_tenant__89bb49_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['tenant', 'email'], name='crm_contact_tenant__8822e3_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['tenant', 'current_stage'], name='crm_lead_tenant__834248_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['tenant', '-created_at'], name='crm_lead_tenant__3b27c1_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['contact', '-created_at'], name='crm_lead_contact_7c89f4_idx'),
        ),
    ]
