# Generated by Django 6.0.5 on 2026-05-08 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='deleted_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['is_deleted'], name='crm_lead_is_dele_ea9493_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['deleted_at'], name='crm_lead_deleted_1073f9_idx'),
        ),
    ]
