# Generated by Django 6.0.5 on 2026-05-09 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_lead_deleted_at_lead_deleted_by_lead_is_deleted_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyFollowupReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('manana', 'Mañana'), ('tarde', 'Tarde')], default='manana', max_length=10)),
                ('date', models.DateField()),
                ('target_leads', models.JSONField(default=list, help_text='Lista de lead_ids a seguir')),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_reports', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-date', '-report_type'],
                'unique_together': {('tenant', 'date', 'report_type')},
            },
        ),
    ]
