# Generated by Django 6.0.5 on 2026-05-10 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_add_tag_leadtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='is_recompra',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
