# Generated by Django 6.0.5 on 2026-05-12 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_add_is_recompra'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KpiTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nombre descriptivo, ej: 'Leads mensuales'", max_length=100)),
                ('metric_type', models.CharField(choices=[('leads', 'Leads totales'), ('conversions', 'Conversiones (Cerrados Ganados)'), ('conversion_rate', 'Tasa de conversión'), ('avg_days', 'Días promedio de cierre')], max_length=30)),
                ('target_value', models.FloatField(help_text='Valor objetivo, ej: 100.0')),
                ('period_type', models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual'), ('quarterly', 'Trimestral')], default='monthly', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_targets', to='tenants.tenant')),
            ],
            options={
                'ordering': ['metric_type', 'period_type'],
            },
        ),
    ]
