# Generated by Django 6.0.5 on 2026-05-13
# Phase 2: migrate metric_type string -> FK, remove old fields, add unique constraint

from django.db import migrations, models


def migrate_metric_type_to_fk(apps, schema_editor):
    KpiMetricType = apps.get_model('crm', 'KpiMetricType')
    KpiTarget = apps.get_model('crm', 'KpiTarget')
    metric_map = {m.slug: m for m in KpiMetricType.objects.all()}
    updated = 0
    for target in KpiTarget.objects.all():
        old_type = target.metric_type
        if old_type and old_type in metric_map:
            target.metric = metric_map[old_type]
            target.save(update_fields=['metric'])
            updated += 1
    print(f"[migration] Updated {updated} KpiTarget records")


def reverse_migration(apps, schema_editor):
    KpiMetricType = apps.get_model('crm', 'KpiMetricType')
    KpiTarget = apps.get_model('crm', 'KpiTarget')
    metric_map = {m.slug: m for m in KpiMetricType.objects.all()}
    for target in KpiTarget.objects.exclude(metric__isnull=True).select_related('metric'):
        target.metric_type = target.metric.slug if target.metric else 'leads'
        target.save(update_fields=['metric_type'])
    print("[migration] Reversed KpiTarget migration")


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_kpimetrictype_model'),
    ]

    operations = [
        migrations.RunPython(migrate_metric_type_to_fk, reverse_migration),
        migrations.RemoveField(model_name='kpitarget', name='metric_type'),
        migrations.RemoveField(model_name='kpitarget', name='name'),
        migrations.AlterField(
            model_name='kpitarget',
            name='metric',
            field=models.ForeignKey(
                on_delete=models.CASCADE,
                related_name='kpi_targets',
                to='crm.KpiMetricType',
            ),
        ),
        migrations.AddConstraint(
            model_name='kpitarget',
            constraint=models.UniqueConstraint(
                fields=['tenant', 'metric', 'period_type'],
                name='unique_tenant_metric_period',
            ),
        ),
    ]