# Generated by Django 6.0.5 on 2026-05-13
# Phase 1: add Product model

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_kpitarget_migrate_metric'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del producto o servicio', max_length=255)),
                ('sku', models.CharField(blank=True, help_text='Codigo SKU del producto', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Precio estandar del producto (COP)', max_digits=14)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='Costo de adquisicion del producto (COP)', max_digits=14, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(help_text='Tenant al que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]