# Generated by Django 6.0.5 on 2026-05-13
# Phase 2: add LeadProduct model

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_product_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Cantidad de unidades')),
                ('unit_price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Precio unitario override (si difiere del precio estandar)', max_digits=14, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_products', to='crm.lead')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_products', to='crm.product')),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Producto en Lead',
                'verbose_name_plural': 'Productos en Leads',
                'unique_together': {('lead', 'product')},
            },
        ),
    ]