# Generated by Django 6.0.5 on 2026-05-13
# Add deal_value column to Lead model

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_leadproduct_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='deal_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Valor monetario estimado del negocio (COP)', max_digits=14, null=True),
        ),
    ]