# Generated by Django 6.0.4 on 2026-07-02 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_lead_deal_value'),
        ('tenants', '0002_tenantuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kpimetrictype',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Tipo de Metric KPI', 'verbose_name_plural': 'Tipos de Metric KPI'},
        ),
        migrations.AlterModelOptions(
            name='kpitarget',
            options={'ordering': ['metric__sort_order', 'period_type']},
        ),
        migrations.AlterModelOptions(
            name='leadproduct',
            options={'verbose_name': 'Producto en Lead', 'verbose_name_plural': 'Productos en Leads'},
        ),
        migrations.RemoveConstraint(
            model_name='kpitarget',
            name='unique_tenant_metric_period',
        ),
        migrations.AlterField(
            model_name='kpimetrictype',
            name='category',
            field=models.CharField(help_text="Grupo: 'volume', 'conversion', 'revenue', 'efficiency'", max_length=50),
        ),
        migrations.AlterField(
            model_name='kpimetrictype',
            name='color',
            field=models.CharField(help_text="Color hex para UI, ej: '#3b82f6'", max_length=7),
        ),
        migrations.AlterField(
            model_name='kpimetrictype',
            name='description',
            field=models.TextField(blank=True, help_text='Descripcion del metric'),
        ),
        migrations.AlterField(
            model_name='kpimetrictype',
            name='icon',
            field=models.CharField(help_text="Clase Bootstrap Icon, ej: 'bi-people'", max_length=50),
        ),
        migrations.AlterField(
            model_name='kpimetrictype',
            name='name',
            field=models.CharField(help_text="Nombre para mostrar, ej: 'Leads totales'", max_length=100),
        ),
        migrations.AlterField(
            model_name='kpimetrictype',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Orden en la UI'),
        ),
        migrations.AlterField(
            model_name='kpimetrictype',
            name='unit',
            field=models.CharField(help_text="Unidad de medida, ej: 'leads', '%', 'dias'", max_length=30),
        ),
        migrations.AlterField(
            model_name='kpitarget',
            name='target_value',
            field=models.FloatField(help_text='Valor objetivo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='tenants.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='kpitarget',
            unique_together={('tenant', 'metric', 'period_type')},
        ),
    ]
