# Generated by Django 6.0.4 on 2026-04-17 00:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wa_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('last_interaction', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='IngestionControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_name', models.CharField(max_length=120, unique=True)),
                ('last_sync_timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=128, unique=True)),
                ('content', models.TextField(blank=True)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('audio', 'Audio'), ('image', 'Image'), ('video', 'Video'), ('other', 'Other')], default='other', max_length=16)),
                ('raw_data', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField()),
                ('processed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ingesta.chatuser')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['external_id'], name='ingesta_mes_externa_c58812_idx'), models.Index(fields=['timestamp'], name='ingesta_mes_timesta_be4876_idx'), models.Index(fields=['message_type'], name='ingesta_mes_message_d3c574_idx')],
            },
        ),
    ]
