# Generated by Django 6.0.4 on 2026-04-17 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingesta', '0002_evolutioninstance_with_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatuser',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
    ]
