# Generated by Django 6.0.4 on 2026-04-17 01:43

from django.db import migrations, models


def backfill_audio_media_fields(apps, schema_editor):
    Message = apps.get_model('ingesta', 'Message')

    for message in Message.objects.filter(message_type='audio').iterator():
        raw_data = message.raw_data if isinstance(message.raw_data, dict) else {}
        payload = raw_data.get('message') if isinstance(raw_data.get('message'), dict) else {}
        audio_payload = {}
        for key in ('audioMessage', 'pttMessage', 'voiceMessage'):
            value = payload.get(key)
            if isinstance(value, dict):
                audio_payload = value
                break
        if not audio_payload:
            for key, value in payload.items():
                if isinstance(value, dict) and any(token in key.lower() for token in ('audio', 'voice', 'ptt')):
                    audio_payload = value
                    break

        media_url = audio_payload.get('url') or audio_payload.get('mediaUrl') or ''
        media_url = str(media_url or '').strip()
        if media_url and not (media_url.startswith('http://') or media_url.startswith('https://')):
            media_url = ''

        media_mime_type = audio_payload.get('mimetype') or audio_payload.get('mimeType') or ''
        media_mime_type = str(media_mime_type or '').strip()

        changed = False
        if media_url and message.media_url != media_url:
            message.media_url = media_url
            changed = True
        if media_mime_type and message.media_mime_type != media_mime_type:
            message.media_mime_type = media_mime_type
            changed = True
        if changed:
            message.save(update_fields=['media_url', 'media_mime_type'])


class Migration(migrations.Migration):

    dependencies = [
        ('ingesta', '0003_chatuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='ingesta/audio/'),
        ),
        migrations.AddField(
            model_name='message',
            name='media_mime_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='message',
            name='media_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.RunPython(backfill_audio_media_fields, migrations.RunPython.noop),
    ]
