# Generated by Django 6.0.4 on 2026-04-17 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingesta', '0004_message_media_file_message_media_mime_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='chat_jid',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='message',
            name='direction',
            field=models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], db_index=True, default='inbound', max_length=16),
        ),
        migrations.AddField(
            model_name='message',
            name='from_me',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='quoted_external_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='message',
            name='recipient_wa_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_wa_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
