# Generated by Django 6.0.4 on 2026-04-17 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingesta', '0005_message_chat_jid_message_direction_message_from_me_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryExecutionControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_key', models.CharField(max_length=40, unique=True)),
                ('slot_start', models.DateTimeField(db_index=True)),
                ('slot_end', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='running', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('detail', models.TextField(blank=True, default='')),
                ('eligible_users', models.PositiveIntegerField(default=0)),
                ('processed_users', models.PositiveIntegerField(default=0)),
                ('skipped_users', models.PositiveIntegerField(default=0)),
                ('failed_users', models.PositiveIntegerField(default=0)),
                ('processed_text_messages', models.PositiveIntegerField(default=0)),
                ('daily_summaries_created', models.PositiveIntegerField(default=0)),
                ('daily_summaries_updated', models.PositiveIntegerField(default=0)),
                ('monthly_summaries_created', models.PositiveIntegerField(default=0)),
                ('monthly_summaries_updated', models.PositiveIntegerField(default=0)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('meta', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-slot_start', '-started_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyTextSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('month', models.PositiveSmallIntegerField(db_index=True)),
                ('text', models.TextField(blank=True, default='')),
                ('has_data', models.BooleanField(default=False)),
                ('pending_items', models.JSONField(default=list)),
                ('mentioned_people', models.JSONField(default=list)),
                ('deadlines', models.JSONField(default=list)),
                ('payment_promises', models.JSONField(default=list)),
                ('source_message_count', models.PositiveIntegerField(default=0)),
                ('source_last_message_ts', models.DateTimeField(blank=True, null=True)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_text_summaries', to='ingesta.chatuser')),
                ('last_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_summaries', to='ingesta.summaryexecutioncontrol')),
            ],
            options={
                'ordering': ['-year', '-month', '-revision'],
                'indexes': [models.Index(fields=['user', 'year', 'month'], name='ingesta_mon_user_id_1a2d09_idx'), models.Index(fields=['year', 'month', 'is_current'], name='ingesta_mon_year_7748d4_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyTextSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_date', models.DateField(db_index=True)),
                ('text', models.TextField(blank=True, default='')),
                ('has_data', models.BooleanField(default=False)),
                ('pending_items', models.JSONField(default=list)),
                ('mentioned_people', models.JSONField(default=list)),
                ('deadlines', models.JSONField(default=list)),
                ('payment_promises', models.JSONField(default=list)),
                ('source_message_count', models.PositiveIntegerField(default=0)),
                ('source_last_message_ts', models.DateTimeField(blank=True, null=True)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_text_summaries', to='ingesta.chatuser')),
                ('last_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_summaries', to='ingesta.summaryexecutioncontrol')),
            ],
            options={
                'ordering': ['-summary_date', '-updated_at'],
                'indexes': [models.Index(fields=['summary_date'], name='ingesta_dai_summary_ffd761_idx'), models.Index(fields=['user', 'summary_date'], name='ingesta_dai_user_id_abfa1e_idx')],
                'unique_together': {('user', 'summary_date')},
            },
        ),
    ]
