# Generated by Django 6.0.4 on 2026-04-18 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingesta', '0007_chatuser_is_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('call', 'Call'), ('note', 'Note'), ('other', 'Other')], default='call', max_length=16)),
                ('from_me', models.BooleanField(db_index=True, default=True)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], db_index=True, default='outbound', max_length=16)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('is_video', models.BooleanField(default=False)),
                ('source', models.CharField(db_index=True, default='csv', max_length=40)),
                ('source_ref', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('content', models.TextField(blank=True, default='')),
                ('raw_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='ingesta.chatuser')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['user', 'occurred_at'], name='ingesta_use_user_id_054778_idx'), models.Index(fields=['source', 'occurred_at'], name='ingesta_use_source_85cf08_idx')],
            },
        ),
    ]
